package handlers

import (
	"encoding/json"
	"net/http"
	"marketplace-backend/database"
	"marketplace-backend/models"
)

func CreateListing(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var listing models.Listing
	if err := json.NewDecoder(r.Body).Decode(&listing); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	stmt, err := database.DB.Prepare("INSERT INTO listings(user_id, title, description, price, category) VALUES(?, ?, ?, ?, ?)")
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	defer stmt.Close()

	res, err := stmt.Exec(listing.UserID, listing.Title, listing.Description, listing.Price, listing.Category)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	id, _ := res.LastInsertId()
	listing.ID = int(id)

	// Fetch the created listing to return proper timestamps (optional, but good practice)
	// For simplicity, we just return what we have plus the ID, or re-query.
	// Let's just return the listing with ID for now as per prompt "Return created listing as JSON".
	// To be accurate with timestamps generated by DB, we should query it back.
	
	err = database.DB.QueryRow("SELECT created_at, updated_at FROM listings WHERE id = ?", id).Scan(&listing.CreatedAt, &listing.UpdatedAt)
	if err != nil {
		// handle error
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	json.NewEncoder(w).Encode(listing)
}
